//! This code was AUTOGENERATED using the Codama library.
//!
//! `carbon-cli` embeds the address of whichever local dev keypair happened
//! to sign target/idl/nebulous_world.json at generation time into
//! `PROGRAM_ID` below (target/ is gitignored and regenerable, so that
//! keypair drifts from `declare_id!` across environments — see the
//! "Program ID mismatch" handling in scripts/setup-dev.sh). `PROGRAM_ID`
//! used to gate `AccountDecoder::decode_account`/`InstructionDecoder::
//! decode_instruction`'s owner checks, silently decoding nothing whenever
//! it went stale relative to the actually-deployed program — see the
//! HAND-PATCHED notes in accounts/mod.rs and instructions/mod.rs for why
//! those checks were removed (redundant with the runtime-configured
//! program id every caller already filters by). Kept here, now unused by
//! this crate itself, only as a reference value.
#![allow(clippy::op_ref, clippy::empty_line_after_doc_comments)] // style nits in codama-generated code
use solana_pubkey::Pubkey;
pub struct NebulousWorldDecoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("EkQRRgRFd2FUedJnPVs2Xs6N7U2Jef5GrfwJ62UJZUXx");

pub mod accounts;
pub mod instructions;
pub mod types;
