//! This code was AUTOGENERATED using the Codama library.
//!
//! HAND-EDITED: `carbon-cli` embedded the address of the local dev keypair
//! that happened to sign target/idl/nebulous_world.json at generation time
//! (target/ is gitignored and regenerable, so that keypair drifts from
//! `declare_id!` across environments — see the "Program ID mismatch"
//! handling in scripts/setup-dev.sh). Patched here to the program's real
//! canonical id (`declare_id!` in programs/nebulous_world/src/lib.rs, same
//! value as NEXT_PUBLIC_NEBULOUS_WORLD_PROGRAM_ID in render.yaml) — this
//! constant gates AccountDecoder::decode_account's owner check, so a wrong
//! value here silently decodes nothing.
#![allow(clippy::op_ref, clippy::empty_line_after_doc_comments)] // style nits in codama-generated code
use solana_pubkey::Pubkey;
pub struct NebulousWorldDecoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("EkQRRgRFd2FUedJnPVs2Xs6N7U2Jef5GrfwJ62UJZUXx");

pub mod accounts;
pub mod instructions;
pub mod types;
