//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct AppAccount {
    /// The variable seed used to derive this PDA (seeds: `[APP_SEED,
    /// app_id.as_bytes()]`). Capped at 32 bytes — see `MAX_APP_ID_LEN` —
    /// since it is also used directly as a PDA seed, which has a hard
    /// 32-byte-per-seed limit. Chosen client-side before this account is
    /// created (there is no off-chain row yet to derive it from), and
    /// reused as the Postgres `App.id` once the indexer indexes this
    /// account.
    pub app_id: String,
    /// The app's URL with the `https://` protocol trimmed off to save
    /// rent-space (every app is assumed to be served over https — see
    /// `indexer/src/api.rs`'s `init_app_ix`, which does the trimming, and
    /// the indexer's account processor, which prepends it back when
    /// mirroring this into Postgres). Capped at `MAX_URL_LEN` bytes.
    pub url: String,
    pub total_vote_stake: u64,
    pub vote_acc_reward_per_share: u128,
    pub total_tag_stake: u64,
    pub tags_acc_reward_per_share: u128,
    /// PDA bump for `[APP_SEED, app_id.as_bytes()]`.
    pub bump: u8,
}

impl AppAccount {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[189, 192, 243, 151, 141, 78, 227, 17] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
