//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct AppTagAccount {
    pub app: Pubkey,
    /// Off-chain tag identifier (a Prisma tag slug). Capped at
    /// `MAX_TAG_ID_LEN` bytes — same PDA-seed constraint as `AppAccount::app_id`.
    pub tag_id: String,
    /// Vault holding this tag's locked stake principal (seeds:
    /// `[TAG_VAULT_SEED, app_tag]`), authority = this `AppTagAccount` PDA.
    pub principal_vault: Pubkey,
    pub stake_amount: u64,
    /// PDA bump. IMPORTANT for CPI signing: this account's derivation seeds
    /// are `[TAG_SEED, app.as_ref(), tag_id.as_bytes()]`, NOT the account's
    /// own pubkey (same footgun class as `AppAccount::bump` — see that
    /// comment). Any instruction that needs this `app_tag` PDA to sign a CPI
    /// (e.g. Task 17's `withdraw_tag_stake`, transferring out of
    /// `principal_vault`, whose `token::authority = app_tag`) must sign with
    /// `&[TAG_SEED, app_tag.app.as_ref(), app_tag.tag_id.as_bytes(), &[app_tag.bump]]`
    /// — using `app_tag.key()` instead of `app_tag.app.as_ref()` will fail
    /// signature verification. Conveniently, `app_tag.app` (the stored field)
    /// already equals the `app.key()` used at derivation time, so reading it
    /// straight off this account (rather than re-deriving or threading
    /// `app_id` through) is both correct and the natural way to build the
    /// seeds.
    /// 
    /// This is a DIFFERENT signing authority from `AppAccount::bump`'s: the
    /// `app` PDA signs for `vote_vault`/`vote_reward_vault`/`tags_reward_vault`,
    /// while the `app_tag` PDA signs only for its own `principal_vault`. Do
    /// not conflate the two when wiring up CPIs.
    pub bump: u8,
}

impl AppTagAccount {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[242, 177, 49, 176, 102, 80, 169, 167] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
