//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct AppAccount {
    /// Off-chain identifier (Prisma cuid) this account was derived from.
    /// Capped at 32 bytes — see `MAX_APP_ID_LEN` — since it is also used
    /// directly as a PDA seed, which has a hard 32-byte-per-seed limit.
    pub app_id: String,
    /// Vault holding locked vote-stake principal (seeds: `[VOTE_VAULT_SEED, app]`).
    pub vote_vault: Pubkey,
    /// Vault holding funded vote-pool rewards awaiting claim (seeds: `[VOTE_REWARD_VAULT_SEED, app]`).
    pub vote_reward_vault: Pubkey,
    /// Vault holding funded tags-pool rewards awaiting claim, shared across
    /// all of this app's tags (seeds: `[TAGS_REWARD_VAULT_SEED, app]`).
    pub tags_reward_vault: Pubkey,
    pub total_vote_stake: u64,
    pub vote_acc_reward_per_share: u128,
    pub total_tag_stake: u64,
    pub tags_acc_reward_per_share: u128,
    /// PDA bump. IMPORTANT for CPI signing: this account's derivation seeds are
    /// `[APP_SEED, app_id.as_bytes()]`, NOT the account's own pubkey. Any
    /// instruction that needs this PDA to sign a CPI (e.g. transferring out of
    /// vote_vault/vote_reward_vault/tags_reward_vault) must sign with
    /// `&[APP_SEED, app_id.as_bytes(), &[bump]]` — using `app.key()` instead of
    /// `app_id.as_bytes()` will fail signature verification.
    pub bump: u8,
}

impl AppAccount {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[189, 192, 243, 151, 141, 78, 227, 17] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
