//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct AppTagStake {
    pub app: Pubkey,
    pub tag: Pubkey,
    pub stake_amount: u64,
    /// PDA bump for `[APP_TAG_STAKE_SEED, app.as_ref(), tag.as_ref()]`.
    pub bump: u8,
}

impl AppTagStake {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[85, 80, 83, 80, 34, 221, 42, 99] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
