//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Config {
    pub authority: Pubkey,
    pub vote_mint: Pubkey,
    /// Set once at `initialize` and validated (`<= 10_000`) there, but not
    /// read by any instruction in this program — no instruction here ever
    /// skims a fee off a transfer. The actual protocol fee is computed and
    /// deducted OFF-CHAIN, on gross ad revenue, before `fund_app_rewards` is
    /// ever called: see `PROTOCOL_FEE` in `app/scripts/settleEpoch.ts` and
    /// `REVENUE_CONFIG.protocolFee` in `app/src/lib/revenue.ts` (the two
    /// must be kept in sync with each other, and this field is not the
    /// source of truth for either). Kept on-chain as a recorded/auditable
    /// parameter of the deployment, not as an enforcement point — do not
    /// assume changing this value would change the effective fee.
    pub protocol_fee_bps: u16,
    pub bump: u8,
}

impl Config {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[155, 12, 170, 224, 30, 250, 204, 130] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
