//! This code was AUTOGENERATED using the Codama library.
use crate::NebulousWorldDecoder;

pub mod app_account;
pub mod app_tag_stake;
pub mod config;
pub mod stake_position;
pub mod tag;
pub mod vote_position;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum NebulousWorldAccount {
    AppAccount(Box<app_account::AppAccount>),
    AppTagStake(Box<app_tag_stake::AppTagStake>),
    Config(Box<config::Config>),
    StakePosition(Box<stake_position::StakePosition>),
    Tag(Box<tag::Tag>),
    VotePosition(Box<vote_position::VotePosition>),
}

impl<'a> carbon_core::account::AccountDecoder<'a> for NebulousWorldDecoder {
    type AccountType = NebulousWorldAccount;
    
    fn decode_account(
        &self,
        account: &'a solana_account::Account,
    ) -> Option<carbon_core::account::DecodedAccount<Self::AccountType>> {
        // HAND-PATCHED: the generated `account.owner != PROGRAM_ID` gate
        // here used the module-level `PROGRAM_ID` constant — hardcoded at
        // codegen time from whatever `target/idl/nebulous_world.json`
        // happened to contain, independent of (and prone to drifting from)
        // the actually-configured `Config::program_id` every caller of
        // this decoder already scopes its account fetches/subscriptions to
        // (see src/backfill.rs's `get_program_accounts(&program_id)` and
        // src/main.rs's `ProgramFilters::new(config.program_id, ...)`).
        // Every `anchor keys sync` (routine in this dev workflow — see
        // scripts/setup-dev.sh) changes the real deployed program id
        // without updating this generated constant, silently decoding zero
        // accounts from that point on. Removed rather than re-patched to a
        // new fixed value: the datasources already guarantee every account
        // handed to this decoder is owned by the configured program, so
        // this check was redundant even when its constant was fresh.
        let data = account.data.as_slice();
        
        {
            if let Some(decoded) = app_account::AppAccount::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: NebulousWorldAccount::AppAccount(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = app_tag_stake::AppTagStake::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: NebulousWorldAccount::AppTagStake(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = config::Config::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: NebulousWorldAccount::Config(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = stake_position::StakePosition::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: NebulousWorldAccount::StakePosition(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = tag::Tag::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: NebulousWorldAccount::Tag(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = vote_position::VotePosition::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: NebulousWorldAccount::VotePosition(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        
        None
    }
}

