//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct NebPool {
    pub mint: Pubkey,
    /// Vault (authority = this PDA) holding unsold NEB. Seeds:
    /// `[NEB_POOL_VAULT_SEED, pool.key()]`.
    pub token_vault: Pubkey,
    /// Total NEB deposited at `init_neb_pool` time — fixed for the pool's
    /// lifetime, never mutated after init.
    pub total_supply: u64,
    /// NEB remaining in `token_vault`. Cached here (rather than requiring a
    /// separate token-account fetch) so quotes can be computed from this
    /// account alone; `buy_neb` keeps it exactly in sync with the vault's
    /// real balance.
    pub remaining_supply: u64,
    /// Real lamports raised so far — sits in this PDA's own SOL balance
    /// (buyers pay via a plain System Program transfer into the PDA).
    pub sol_raised: u64,
    /// Constant-product curve's virtual SOL-side reserve, fixed at init and
    /// never mutated afterward — never actually deposited, exists purely so
    /// a single-sided pool has a well-defined starting price. Effective SOL
    /// reserve at any point is `virtual_sol_reserves + sol_raised`;
    /// effective token reserve is `remaining_supply` (no virtual token side,
    /// since the entire `total_supply` was genuinely deposited).
    pub virtual_sol_reserves: u64,
    pub bump: u8,
}

impl NebPool {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[176, 18, 18, 237, 15, 128, 73, 185] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
