//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct StakePosition {
    pub app_tag_stake: Pubkey,
    pub owner: Pubkey,
    pub payer: Pubkey,
    pub amount: u64,
    pub reward_debt: u128,
    /// Size-weighted-average deposit timestamp (Unix seconds) — see
    /// `unstake_fee::weighted_avg_timestamp`. Drives `withdraw_tag_stake`'s
    /// linearly-decaying unstake fee (`unstake_fee.rs`), the tag-staking
    /// mirror of `VotePosition::staked_at` — see that field's doc comment.
    pub staked_at: i64,
    pub bump: u8,
}

impl StakePosition {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[78, 165, 30, 111, 171, 125, 11, 220] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
