//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Tag {
    /// The variable seed used to derive this PDA. Capped at
    /// `MAX_TAG_ID_LEN` (32) bytes — same PDA-seed constraint as
    /// `AppAccount::app_id`.
    pub tag_id: String,
    /// PDA bump for `[TAG_SEED, tag_id.as_bytes()]`.
    pub bump: u8,
}

impl Tag {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[145, 209, 53, 147, 161, 98, 8, 114] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
