//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct VotePosition {
    pub app: Pubkey,
    pub owner: Pubkey,
    pub payer: Pubkey,
    pub amount: u64,
    pub reward_debt: u128,
    /// Size-weighted-average deposit timestamp (Unix seconds) — see
    /// `unstake_fee::weighted_avg_timestamp`. Drives `withdraw_vote`'s
    /// linearly-decaying unstake fee (`unstake_fee.rs`): 1% immediately
    /// after a deposit, decaying to 0% over the following week. Updated on
    /// every `vote()` deposit; left unchanged by a withdrawal (a partial
    /// withdrawal doesn't reset the remaining balance's age).
    pub staked_at: i64,
    pub bump: u8,
}

impl VotePosition {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[121, 54, 167, 23, 147, 96, 61, 209] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
