//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct BuyNeb {
    pub sol_amount: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BuyNebInstructionAccounts {
    pub pool: solana_pubkey::Pubkey,
    pub token_vault: solana_pubkey::Pubkey,
    pub buyer_token_account: solana_pubkey::Pubkey,
    pub buyer: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl BuyNeb {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[4, 17, 221, 151, 233, 167, 84, 167] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for BuyNeb {
    type ArrangedAccounts = BuyNebInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let pool = next_account(&mut iter)?;
        let token_vault = next_account(&mut iter)?;
        let buyer_token_account = next_account(&mut iter)?;
        let buyer = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(BuyNebInstructionAccounts {
            pool,
            token_vault,
            buyer_token_account,
            buyer,
            token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
