//! This code was AUTOGENERATED using the Codama library.
use crate::types::RewardPool;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct FundAppRewards {
    pub pool: RewardPool,
    pub amount: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FundAppRewardsInstructionAccounts {
    pub app: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub vote_reward_vault: solana_pubkey::Pubkey,
    pub tags_reward_vault: solana_pubkey::Pubkey,
    pub funder_token_account: solana_pubkey::Pubkey,
    pub authority: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl FundAppRewards {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[247, 160, 182, 238, 153, 20, 140, 241] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for FundAppRewards {
    type ArrangedAccounts = FundAppRewardsInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let app = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let vote_reward_vault = next_account(&mut iter)?;
        let tags_reward_vault = next_account(&mut iter)?;
        let funder_token_account = next_account(&mut iter)?;
        let authority = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(FundAppRewardsInstructionAccounts {
            app,
            config,
            vote_reward_vault,
            tags_reward_vault,
            funder_token_account,
            authority,
            token_program,
            remaining: remaining.to_vec(),
        })
    }
}
