//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct InitNebPool {
    pub total_supply: u64,
    pub virtual_sol_reserves: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitNebPoolInstructionAccounts {
    pub config: solana_pubkey::Pubkey,
    pub pool: solana_pubkey::Pubkey,
    pub token_vault: solana_pubkey::Pubkey,
    pub vote_mint: solana_pubkey::Pubkey,
    pub authority_token_account: solana_pubkey::Pubkey,
    pub authority: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl InitNebPool {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[212, 21, 128, 245, 6, 168, 106, 220] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for InitNebPool {
    type ArrangedAccounts = InitNebPoolInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let config = next_account(&mut iter)?;
        let pool = next_account(&mut iter)?;
        let token_vault = next_account(&mut iter)?;
        let vote_mint = next_account(&mut iter)?;
        let authority_token_account = next_account(&mut iter)?;
        let authority = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(InitNebPoolInstructionAccounts {
            config,
            pool,
            token_vault,
            vote_mint,
            authority_token_account,
            authority,
            token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
