//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct InitApp {
    pub app_id: String,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitAppInstructionAccounts {
    pub app: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub vote_vault: solana_pubkey::Pubkey,
    pub vote_reward_vault: solana_pubkey::Pubkey,
    pub tags_reward_vault: solana_pubkey::Pubkey,
    pub vote_mint: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl InitApp {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[126, 7, 32, 62, 17, 43, 172, 107] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for InitApp {
    type ArrangedAccounts = InitAppInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let app = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let vote_vault = next_account(&mut iter)?;
        let vote_reward_vault = next_account(&mut iter)?;
        let tags_reward_vault = next_account(&mut iter)?;
        let vote_mint = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(InitAppInstructionAccounts {
            app,
            config,
            vote_vault,
            vote_reward_vault,
            tags_reward_vault,
            vote_mint,
            payer,
            token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
