//! This code was AUTOGENERATED using the Codama library.
use crate::NebulousWorldDecoder;
use crate::PROGRAM_ID;

pub mod buy_neb;
pub mod claim_tag_reward;
pub mod claim_vote_reward;
pub mod fund_app_rewards;
pub mod init_app;
pub mod init_neb_pool;
pub mod initialize;
pub mod stake_tag;
pub mod suggest_tag;
pub mod vote;
pub mod withdraw_pool_sol;
pub mod withdraw_tag_stake;
pub mod withdraw_vote;

pub use self::buy_neb::*;
pub use self::claim_tag_reward::*;
pub use self::claim_vote_reward::*;
pub use self::fund_app_rewards::*;
pub use self::init_app::*;
pub use self::init_neb_pool::*;
pub use self::initialize::*;
pub use self::stake_tag::*;
pub use self::suggest_tag::*;
pub use self::vote::*;
pub use self::withdraw_pool_sol::*;
pub use self::withdraw_tag_stake::*;
pub use self::withdraw_vote::*;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum NebulousWorldInstruction {
    BuyNeb(BuyNeb),
    ClaimTagReward(ClaimTagReward),
    ClaimVoteReward(ClaimVoteReward),
    FundAppRewards(FundAppRewards),
    InitApp(InitApp),
    Initialize(Initialize),
    InitNebPool(InitNebPool),
    StakeTag(StakeTag),
    SuggestTag(SuggestTag),
    Vote(Vote),
    WithdrawPoolSol(WithdrawPoolSol),
    WithdrawTagStake(WithdrawTagStake),
    WithdrawVote(WithdrawVote),
}

impl carbon_core::instruction::InstructionDecoder<'_> for NebulousWorldDecoder {
    type InstructionType = NebulousWorldInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if !instruction.program_id.eq(&PROGRAM_ID) {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = buy_neb::BuyNeb::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::BuyNeb(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_tag_reward::ClaimTagReward::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::ClaimTagReward(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_vote_reward::ClaimVoteReward::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::ClaimVoteReward(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = fund_app_rewards::FundAppRewards::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::FundAppRewards(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = init_app::InitApp::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::InitApp(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = init_neb_pool::InitNebPool::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::InitNebPool(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize::Initialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::Initialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = stake_tag::StakeTag::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::StakeTag(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = suggest_tag::SuggestTag::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::SuggestTag(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = vote::Vote::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::Vote(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = withdraw_pool_sol::WithdrawPoolSol::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::WithdrawPoolSol(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = withdraw_tag_stake::WithdrawTagStake::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::WithdrawTagStake(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = withdraw_vote::WithdrawVote::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::WithdrawVote(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
