//! This code was AUTOGENERATED using the Codama library.
use crate::NebulousWorldDecoder;

pub mod claim_tag_reward;
pub mod claim_vote_reward;
pub mod fund_app_rewards;
pub mod init_app;
pub mod initialize;
pub mod stake_tag;
pub mod suggest_tag;
pub mod vote;
pub mod withdraw_tag_stake;
pub mod withdraw_vote;

pub use self::claim_tag_reward::*;
pub use self::claim_vote_reward::*;
pub use self::fund_app_rewards::*;
pub use self::init_app::*;
pub use self::initialize::*;
pub use self::stake_tag::*;
pub use self::suggest_tag::*;
pub use self::vote::*;
pub use self::withdraw_tag_stake::*;
pub use self::withdraw_vote::*;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum NebulousWorldInstruction {
    ClaimTagReward(ClaimTagReward),
    ClaimVoteReward(ClaimVoteReward),
    FundAppRewards(FundAppRewards),
    InitApp(InitApp),
    Initialize(Initialize),
    StakeTag(StakeTag),
    SuggestTag(SuggestTag),
    Vote(Vote),
    WithdrawTagStake(WithdrawTagStake),
    WithdrawVote(WithdrawVote),
}

impl carbon_core::instruction::InstructionDecoder<'_> for NebulousWorldDecoder {
    type InstructionType = NebulousWorldInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        // HAND-PATCHED — see the matching note on accounts/mod.rs's
        // `decode_account`: this generated `program_id != PROGRAM_ID` gate
        // used a codegen-time-hardcoded constant, independent of (and
        // prone to drifting from) the runtime-configured program id every
        // caller already filters by (see src/crawler.rs:200's
        // `ix_program_id != program_id` check, which runs before this
        // decoder is ever invoked). Removed for the same reason: redundant
        // even when fresh, and silently drops everything once it goes stale.
        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = claim_tag_reward::ClaimTagReward::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::ClaimTagReward(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_vote_reward::ClaimVoteReward::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::ClaimVoteReward(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = fund_app_rewards::FundAppRewards::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::FundAppRewards(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = init_app::InitApp::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::InitApp(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize::Initialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::Initialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = stake_tag::StakeTag::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::StakeTag(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = suggest_tag::SuggestTag::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::SuggestTag(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = vote::Vote::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::Vote(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = withdraw_tag_stake::WithdrawTagStake::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::WithdrawTagStake(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = withdraw_vote::WithdrawVote::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: NebulousWorldInstruction::WithdrawVote(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
