//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct SuggestTag {
    pub app_id: String,
    pub tag_id: String,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SuggestTagInstructionAccounts {
    pub app: solana_pubkey::Pubkey,
    pub app_tag: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub principal_vault: solana_pubkey::Pubkey,
    pub vote_mint: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl SuggestTag {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[192, 92, 24, 181, 145, 125, 233, 31] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for SuggestTag {
    type ArrangedAccounts = SuggestTagInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let app = next_account(&mut iter)?;
        let app_tag = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let principal_vault = next_account(&mut iter)?;
        let vote_mint = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(SuggestTagInstructionAccounts {
            app,
            app_tag,
            config,
            principal_vault,
            vote_mint,
            payer,
            token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
