//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct WithdrawTagStake {
    pub amount: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct WithdrawTagStakeInstructionAccounts {
    pub app: solana_pubkey::Pubkey,
    pub app_tag: solana_pubkey::Pubkey,
    pub position: solana_pubkey::Pubkey,
    pub principal_vault: solana_pubkey::Pubkey,
    pub tags_reward_vault: solana_pubkey::Pubkey,
    pub user_token_account: solana_pubkey::Pubkey,
    pub user: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl WithdrawTagStake {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[56, 134, 3, 156, 20, 123, 219, 197] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for WithdrawTagStake {
    type ArrangedAccounts = WithdrawTagStakeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let app = next_account(&mut iter)?;
        let app_tag = next_account(&mut iter)?;
        let position = next_account(&mut iter)?;
        let principal_vault = next_account(&mut iter)?;
        let tags_reward_vault = next_account(&mut iter)?;
        let user_token_account = next_account(&mut iter)?;
        let user = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(WithdrawTagStakeInstructionAccounts {
            app,
            app_tag,
            position,
            principal_vault,
            tags_reward_vault,
            user_token_account,
            user,
            token_program,
            remaining: remaining.to_vec(),
        })
    }
}
