//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct WithdrawVote {
    pub amount: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct WithdrawVoteInstructionAccounts {
    pub app: solana_pubkey::Pubkey,
    pub position: solana_pubkey::Pubkey,
    pub vote_vault: solana_pubkey::Pubkey,
    pub vote_reward_vault: solana_pubkey::Pubkey,
    pub user_token_account: solana_pubkey::Pubkey,
    pub user: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl WithdrawVote {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[243, 255, 70, 200, 3, 242, 103, 137] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for WithdrawVote {
    type ArrangedAccounts = WithdrawVoteInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let app = next_account(&mut iter)?;
        let position = next_account(&mut iter)?;
        let vote_vault = next_account(&mut iter)?;
        let vote_reward_vault = next_account(&mut iter)?;
        let user_token_account = next_account(&mut iter)?;
        let user = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(WithdrawVoteInstructionAccounts {
            app,
            position,
            vote_vault,
            vote_reward_vault,
            user_token_account,
            user,
            token_program,
            remaining: remaining.to_vec(),
        })
    }
}
